language: java
jdk: openjdk8

services:
  - docker

jobs:
  include:
    - stage: "package"
      name: "Build JAR"
      script: ./mvnw package
    - stage: "docker-build-push"
      name: "Build and Push Docker Image"
      script: 
        - docker build -t betorcs/cdrgen .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push betorcs/cdrgen

