language: java
jdk: openjdk8

services:
  - docker

jobs:
  include:
    - stage: "package"
      name: "Build JAR"
      script: ./mvnw package
    - stage: "docker-build-push"
      name: "Build and Push Docker Image"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - IMAGE="$IMAGE_NAME:$TRAVIS_TAG"
        - docker build -t $IMAGE .
        - docker push $IMAGE

